### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by djfurman** [MazenAB/glue-immersion-instructions#1]
Thanks for putting this together, @MazenAB!

I really like the content, and it's a fantastic way to get into coding with Glue.

I'd to contribute to some of the Python code examples in your instructions with some of the f-string practices to enhance readability as well as some formatting.

Would you consider adding a license to this repo so I can send you a contribution?

**Comment by MazenAB** [comment]
@djfurman, Thank you so much for your offer. I created this repo on a temporary basis and will have it private at the end of today. I can provide more info privately

**Comment by djfurman** [comment]
Thank you!
